scieloorg/core

.envs/.local/.postgres, local.yml, requirements/base.txt
Renomeia containers e base posgres para `scielo_core`
Adiciona o _Django Celery_ nas dependências
Nos commits
Aplicar as migrações para verificar a criação da base.
=> Renomeando containers e base postgres

core/home/models.py, core/models.py, location/models.py
Troca o valor do atributo `on_delete` de `CASCADE` para `SET_NULL`.
Por _commit_.
NA.
As trocas sugeridas em `core` devem ser verificadas.
NA.
NA.
NA.
=> Change attrib value

journal_and_collection/admin.py, journal_and_collection/apps.py, journal_and_collection/choices.py, journal_and_collection/forms.py, journal_and_collection/models.py, journal_and_collection/tests.py, journal_and_collection/views.py, journal_and_collection/wagtail_hooks.py
Adiciona modelo para armazenar a associação entre periódicos e coleções.
Por _commit_.
Para testar há dependência da incorporação do PR #27 que adiciona o modelo para periódicos.
NA.
NA.
TK #26.
NA.
=> Create Journal and collection model

compose/local/docs/Dockerfile, local.yml
bugfix: Descomenta container docs e corrige o bug em Dockerfile.
Corrige o bug em Dockerfile para rodar o container docs.
Lendo o commit.
Rode os comandos
```
make stop
make build_no_cache
make up
```
NA
NA
#101
NA
=> bugfix: Descomenta container docs e corrige o bug em Dockerfile

requirements/base.txt, requirements/local.txt
Corrige erros após aprovar os PR do dependabot
Bump flake8-isort from 4.1.1 to 6.0.0
https://github.com/scieloorg/core/pull/84
Bump flower from 1.0.0 to 1.2.0
https://github.com/scieloorg/core/pull/83
Bump werkzeug[watchdog] from 2.0.3 to 2.2.3
https://github.com/scieloorg/core/pull/85
Lendo o commit.
Rode os comandos
```
make stop
make build_no_cache
make up
docker container logs scielo_core_local_django
```
NA
NA
#104
NA
=> bugfix: Corrige erros após aprovar os PR do dependabot

.pre-commit-config.yaml
Atualiza versão das libs usadas em .pre-commit-config.yaml para corrigir os erros no CI.
Lendo os commits.
Conferindo se passam os checks em cada PR.
NA
NA
#100
NA
=> Atualiza versão das libs usadas em .pre-commit-config.yaml para corrigir os erros no CI

compose/production/postgres/Dockerfile
=> fix: Volta o postgres para a versão anterior 14.1

requirements/base.txt
=> Atualiza versão do Django para 4.1.8

compose/production/postgres/Dockerfile
Atualiza PostgreSQL para v14.7.
Lendo os commits.
```
make up
make django_migrate
docker container logs scielo_core_local_django
```
NA
NA
NA
NA
=> Atualiza PostgreSQL para v14.7

core/models.py
Corrige o nome do campo text para plain_text e rich_text
=> Corrige o nome do campo text para plain_text e rich_text

article/tasks.py
corrige erro na task load_articles
pelos commits
1. make django_bash
2. python manage.py runscript load_article
N/A
N/A
N/A
N/A
=> corrige erro na task load_articles

requirements/base.txt
=> Revert "Bump django from 4.1.8 to 4.2.3"

requirements/base.txt, requirements/local.txt
Atualiza algumas dependencias django 4.1.10 | wagtail 4.2.3 | celery 5.3.1 | etc
=> Atualiza algumas dependencias django 4.1.10 | wagtail 4.2.3 | celery 5.3.1 | etc

article/utils/parse_name_author.py, book/models.py, book/utils/utils.py, doi/models.py, pid_provider/wagtail_hooks.py, researcher/models.py, researcher/wagtail_hooks.py, xmlsps/models.py, xmlsps/wagtail_hooks.py, xmlsps/xml_sps_lib.py
Corrige importações de módulos do wagtail que ficarão obsoletos
Por commits
Ao subir os containers as mensagens de warning / deprecation não devem mais ser apresentadas
As versões de Django e Wagtail ainda não são as mais recentes
n/a
n/a
n/a
=> Corrige importações de módulos do wagtail que ficarão obsoletos

pid_provider/models.py
Corrige a chamada a adapt_query_params e usa seu retorno como parâmetro de cls.objects.get()
=> Corrige a chamada a adapt_query_params e usa seu retorno como parâmetro de cls.objects.get()

xmlsps/models.py
Corrige XMLVErsion.get pois deve considerar que há repetição de pid v3 e finger_print
por commits
Executando os comandos:
```console
curl -X POST http://localhost:8000/api/v2/auth/token/ --data 'username=adm&password=x'
```
```console
curl -X POST -S \
-H "Content-Disposition: attachment;filename=am.xml.zip" \
-F "file=@pid_provider/fixtures/versions/am.xml.zip;type=application/zip" \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkxMzIyNzkyLCJpYXQiOjE2OTEzMTkxOTIsImp0aSI6IjdiZWQzZmIwZWQ2OTRmYjM5MGJlYjZiNzFjMDhmODc5IiwidXNlcl9pZCI6MX0.biMHZ-mPPITUzt6gjbBhBDEiWzhqCWl1veemtkOWLCs' \
```
n/a
n/a
n/a
n/a
=> Corrige XMLVErsion.get pois deve considerar que há repetição de pid v3 e finger_print

pid_provider/controller.py, pid_provider/models.py, pid_provider/sources/am.py, pid_provider/sources/harvesting.py, pid_provider/tasks.py
Registra unexpected events para pid_provider.tasks
por commits
Executando as tasks de pid_provider
n/a
n/a
n/a
n/a
=> [Pid provider] registra unexpected events

pid_provider/controller.py, pid_provider/models.py, pid_provider/scripts/provide_pid_for_am_xmls.py, pid_provider/sources/harvesting.py, pid_provider/tasks.py, pid_provider/wagtail_hooks.py
Pid provider registra unexpected events em controller e models
por commits
Executando as tasks de pid_provider
n/a
n/a
n/a
n/a
=> [Pid provider] registra unexpected events parte 2

bigbang/scripts/start.py, bigbang/tasks.py, collection/models.py, config/settings/base.py
Cria tarefa que configura o sistema
por commits
Executando:
```console
make django_shell
```
```python
from bigbang.tasks import task_start
task_start(username="adm")
```
ou pela interface administrativa:
- acessando pelo menu Tasks > Periodic Tasks
- adicionando nova tarefa
- preenchendo o formulário com task_start
- parâmetros: `{"username": "adm"}`
- salvar registro
- clicar "Run"
Por enquanto, a única ação é ingressar dados de coleções no sistema, obtendo-os do Articlemeta
n/a
n/a
n/a
=> Cria tarefa que configura o sistema

bigbang/tasks.py, core/models.py, core/routers.py, core/utils/rename_dictionary_keys.py, core/wagtail_hooks.py
Cria Language.load para carregar uma lista inicial de idiomas
Adiciona esta operação na tarefa task_start
por commits
```console
make django_shell
```
```python
from django.contrib.auth import get_user_model
User = get_user_model()
user = User.objects.get(username='adm')
from core.models import *
Language.objects.all().delete()
Language.load(user)
Language.objects.count()
```
n/a
n/a
n/a
n/a
=> Cria Language.load para carregar uma lista inicial de idiomas

bigbang/tasks.py, journal/models.py, journal/sources/am_to_core.py
Cria Standard.load para carregar uma lista inicial de padrões usados pelos periódicos
Adiciona esta operação na tarefa task_start
por commits
```console
make django_shell
```
```python
from django.contrib.auth import get_user_model
User = get_user_model()
user = User.objects.get(username='adm')
from core.models import *
Standard.objects.all().delete()
Standard.load(user)
Standard.objects.count()
```
Outra forma de testar é:
- Acesse a área administrativa
- Acesse o menu Tasks > Periodic Tasks
- Adicione uma task
- Complete o campo de kwargs com {"username": "adm"} (sendo adm um usuário cadastrado)
- Salve
- Execute a tarefa clicando em Run
n/a
n/a
n/a
n/a
=> Journal standard load

journal/models.py
Corrige journal.Standard.load
por commits
=> Corrige journal.Standard.load

article/wagtail_hooks.py, issue/wagtail_hooks.py, journal/wagtail_hooks.py
Em article, OfficialJournal, Journal e ScieloJournal Inclui "created" e "updated" em list_display.
pelo commit
1. make up
2. acessa: http://0.0.0.0:8000/admin/journal/journal/
N/A
https://github.com/scieloorg/core/issues/404
N/A
=> Inclui created e updated em list_display

bigbang/tasks.py, journal/models.py, journal/wagtail_hooks.py, location/models.py
Cria área administrativa / formulários e classmethod load para os modelos que representam uma lista controlada
pelos commits
1. make build
2. make up
3. make django_bash
3.1. python manage.py runscript start --scripts-args 1
N/A
https://github.com/scieloorg/core/issues/403
N/A
=> Cria área administrativa / formulários e classmethod load para os modelos que representam uma lista controlada

journal/models.py
Quita el campo Editorial Manager de la pestaña Related Institutions de Journal
por commit
Revisión de pestaña Related Institutions
N/A
https://github.com/scieloorg/core/issues/394
N/A
=> Quita campo Editorial Manager

core/models.py, journal/models.py
Corrige apresentação de licença de uso no formulário de Journal
por commits
Acessando o formulário de Journal e a aba Formal Information
n/a
n/a
n/a
n/a
=> Corrige apresentação de licença de uso no formulário de Journal

article/tasks.py
Corrige article.tasks.load_articles
por commits
Executando a tarefa article.tasks.load_articles
Pelo script:
```console
make django_bash
python manage.py runscript load_articles --script-args 1
```
ou   agendando a mesma tarefa pela área administrativa
n/a
n/a
n/a
n/a
=> Corrige article.tasks.load_articles

core/models.py, journal/models.py, journal/scripts/load_journal_from_article_meta.py, journal/sources/am_to_core.py, journal/sources/classic_website.py, journal/tasks.py, journal/wagtail_hooks.py
Realiza melhorias na área administrativa de journals
- adiciona filtros à listagem
- reduz a quantidade de itens apresentados por página
- reorganiza as abas
- adiciona indexes
- corrige a coleta, removendo a atribuição de valor para ISSN-L
por commits
Acessando a área administrativa de Journal
na minha máquina está lenta a apresentação da listagem e do formulário
n/a
n/a
n/a
=> Realiza melhorias na área administrativa de journals

journal/sources/am_to_core.py, location/models.py, location/wagtail_hooks.py
Refatoração de location. Mudança de lógica de Country.get e Location.get
por commits
n/a
n/a
n/a
n/a
n/a
=> Refatoração de location

institution/models.py
Corrige Institution.get que deve consultar a combinação de instutition + location
por commits
n/a
n/a
n/a
n/a
n/a
=> Corrige Institution.get

bigbang/tasks.py, journal/fixture/subjects_categories_wok.csv, journal/models.py, journal/sources/am_to_core.py, journal/wagtail_hooks.py
Cria metodo WebOfKnowledgeSubjectCategory.load
pelos commits
1. make up
2. make django_bash
3. python manage.py runscript start --script-args admin
N/A
N/A
https://github.com/scieloorg/core/issues/417
N/A
=> Cria metodo WebOfKnowledgeSubjectCategory.load

journal/sources/am_to_core.py
Aplica o City.standardize, State.standardize, Country.standardize
por commits
Executando a carga de artigos
n/a
n/a
n/a
n/a
=> Aplica o City.standardize, State.standardize, Country.standardize

core/models.py
Adiciona Gender._get, Gender._create, Gender.get_or_create
Por commits
n/a
n/a
n/a
n/a
n/a
=> Adiciona Gender._get, Gender._create, Gender.get_or_create

researcher/models.py
Adiciona a property Researcher.orcid
por commits
```console
make django_shell
```
```python
from researcher.models import *
from django.contrib.auth import get_user_model
User = get_user_model()
user = User.objects.first()
researcher = Researcher.create_or_update(
user,
given_names="Nome",
last_name="Sobrenome",
suffix=None,
declared_name=None,
affiliation=None,
year=None,
orcid="orcid",
lattes=None,
other_ids=None,
email=None,
gender=None,
gender_identification_status=None,
)
print(researcher.orcid == "orcid")
```
n/a
n/a
n/a
n/a
=> Adiciona a property Researcher.orcid

article/sources/xmlsps.py, location/models.py, researcher/models.py
Ao executar load_articles, cria researcher com afiliação
Por commits
Executando a tarefa ou o script load_articles
n/a
n/a
n/a
n/a
=> Ao executar load_articles, cria researcher com afiliação

compose/production/django/Dockerfile
Corrige a versão do python para ambiente de produção (ficou diferente do ambiente de desenvolvimento)
=> Corrige a versão do python para ambiente de produção (ficou diferente do ambiente de desenvolvimento)

local.yml
Altera as portas de local.yml para trabalhar em conjunto com opac e upload sem conflitos de portas
=> Altera as portas de local.yml para trabalhar em conjunto com opac e upload sem conflitos de portas

local.yml
Altera as portas para executar em conjunto core, upload e opac
Em geral coloca 9 como último dígito
=> Altera as portas para executar em conjunto core, upload e opac

config/settings/base.py, tracker/tasks.py
=> Cria task delete_unexpected_events  e Cria a variável de ambiente USE_SOLR

journalpage/templates/journalpage/about.html, journalpage/templates/journalpage/base.html, journalpage/templates/journalpage/includes/contact_footer.html, journalpage/templates/journalpage/includes/levelMenu.html
Atualizar de Links de Navegação no Template Sobre o Periódico para '#'.
https://github.com/scieloorg/core/commit/11242464a19751f6896f3b6e088e3328cf9d7dff
N/A
N/A
N/A
N/A
=> Atualização de Links de Navegação no Template Sobre o Periódico para '#'"

collection/wagtail_hooks.py
Melhoria de UX na área administrativa de collection
por commits
consultando Collection
n/a
Relacionado com #533 
n/a
=> [Melhoria UX] na área administrativa de collection

journal/models.py
Substituição do Componente FieldPanel por AutocompletePanel em contact_location
Pelo commit https://github.com/scieloorg/core/commit/6a3bb0bd063b7bf814e606fc51618554cca5212d
1. make up
2. Acessa: http://0.0.0.0:8009/admin/journal/journal/edit/{id_journal}
N/A
N/A
https://github.com/scieloorg/core/issues/565
N/A
=> Substituição do Componente FieldPanel por AutocompletePanel em contact_location

pid_provider/models.py, requirements/base.txt
Mantém Pid provider compatível com upload
=> Mantém Pid provider compatível com upload

pid_provider/models.py
Modifica pid_provider.models.PidProviderXML.register, verifica novamente skip_registration após completar pids
=> Modifica pid_provider.models.PidProviderXML.register, verifica novamente skip_registration após completar pids

bigbang/tasks.py, bigbang/utils/scheduler.py
Cria agendador de tarefas
por commits
- Acessar a área restrita
- Criar um crontab
- Criar uma tarefa nova usando `bigbang.tasks.task_create_tasks` e preenchendo kwargs com https://github.com/scieloorg/core/wiki/Task-bigbang.tasks.task_create_tasks
- Execute a tarefa criada
- Observe que as tarefas serão criadas
Caso esta tarefa seja reexecutada, apenas atualizará as existentes.
n/a
n/a
n/a
=> Cria agendador de tarefas

bigbang/tasks.py
Adiciona try/except na tarefa task_start
por commits
Executando a tarefa start pela interface administrativa ou 
```console
python manage.py runscript start --script-args adm
```
n/a
n/a
n/a
n/a
=> Adiciona try/except na tarefa task_start

article/sources/xmlsps.py, article/utils/parse_name_author.py, journal/sources/am_to_core.py
Cria uma funcao "get_safe_value" para evitar erro de NoneType.
Pelos commits
1. make up
2. make django_bash
3. python manage.py runscript load_articles --script-args admin
N/A
N/A
N/A
N/A
=> Fix create or update researcher

index/data/core/conf/managed-schema.xml, index/data/core/conf/solrconfig.xml
Ajusta campos que errados entre o repositório e o ambiente de produção do projeto **core**.
=> Ajuste campos nos arquivo de configuração do Solr.

article/sources/xmlsps.py
Corrige as importações  dependentes das importações de article.models
Estava causando erro em load_articles pela ausência de models.OffiicialJournal
A importação no padrão:
```python
from article import models
```
omitir defeitos de importações nas IDEs
por commits
Executando load_articles
n/a
n/a
n/a
n/a
=> Corrige as importações  dependentes das importações de article.models

config/settings/production.py
Adiciona todas as variáveis possíveis para EMAIL.
=> Adiciona todas as variáveis possíveis para EMAIL.

article/tasks.py
Remove o parâmetro xml da task load_article e adiciona na lista de carga de artigos aqueles cujo status é is_valid = False.
Isso corrige o problema de travar a fila de tarefas no redis.
Por commits
Executando a tarefa load_articles
n/a
n/a
n/a
n/a
=> Remove o parâmetro xml da task load_article e adiciona na lista de carga de artigos aqueles cujo status é is_valid = False

pid_provider/tasks.py
Revisa os parâmetros de todas as tasks para que não tenham valores grandes
por commits
Executando os scripts:
```console
python manage.py runscript provide_pid_for_opac_xmls --script-args adm 1900-01-01 2023-12-21 100 1000
python manage.py runscript provide_pid_for_am_xmls --script-args adm '["mex", "chl"]' 1000 99999
```
n/a
n/a
n/a
n/a
=> Revisa os parâmetros das tarefas de pid_provider

article/models.py, article/sources/xmlsps.py, institution/models.py, pid_provider/models.py
Corrige problemas encontrados na carga de dados de artigos
Por commits
Executando o script
```console
make django_bash
```
```console
python manage.py runscript load_articles --script-args adm
```
n/a
n/a
n/a
n/a
=> Corrige problemas encontrados na carga de dados de artigos

journal/sources/am_to_core.py, journal/sources/article_meta.py
Tarea para obtener logos de las revistas
Por commit
N/A
N/A
https://github.com/scieloorg/core/issues/524
N/A
=> Obtención de logos de revistas

journal/models.py
Adiciona f-string nos Métodos  '__str__' de Journal e OfficialJournal
=> Adiciona f-string nos Métodos  '__str__' de Journal e OfficialJournal

institution/models.py, institution/wagtail_hooks.py
Corrige e melhora área administrativa de Institution:
- adiciona coluna e campos para pesquisa: location
- troca FieldPanel por AutocompletePanel
por commits
Acessando a área administrativa de Institution
n/a
n/a
n/a
n/a
=> Corrige e melhora área administrativa de Institution

journal/models.py
Adiciona verificação de nulidade em métodos unicode e str
=> Adiciona verificação de nulidade em métodos unicode e str

journal/choices.py, journal/models.py, journal/wagtail_hooks.py
Corrige texto em STANDARD
pelo commits
N/A
#671 
N/A
=> Corrige texto em STANDARD

editorialboard/models.py, journalpage/templates/journalpage/about.html
Corrigir a formatação condicional de vírgulas e pipes em listas de membros editoriais 
Pelos commits
1. make up 
2. Acessa sobre periodico 
N/A
#677 
N/A
=> Corrigir a formatação condicional de vírgulas e pipes em listas de membros editoriais 

issue/models.py
Melhora a apresentação de Issue.__str__
=> Melhora a apresentação de Issue.__str__

article/sources/xmlsps.py, article/tasks.py
Corrige a obtenção da data do item caso item é None
por commits
Executando a carga de artigo
n/a
n/a
n/a
=> Corrige a obtenção da data do item caso item é None

journal/sources/am_to_core.py
Adiciona a chamada para a tarefa que carrega o logo do periódico
=> Adiciona a chamada para a tarefa que carrega o logo do periódico

institution/wagtail_hooks.py, journal/wagtail_hooks.py
Disponibiliza Owner, Copyrightholder e Publisher na area administrativa
pelos commits
Acessando menu administrativo
N/A
#692 
N/A
=> Disponibiliza Owner, Copyrightholder e Publisher na area administrativa

index/data/core/conf/managed-schema.xml
No arquivo de configuracao managed-schema.xml, insere configuracoes de busca e tokenizacao ao campo 'text'.
pelo commit
```
python manage.py update_index
```
N/A
N/A
#705 
https://github.com/scieloorg/core/issues/695
N/A
=> No arquivo de configuracao managed-schema.xml, insere configuracoes de busca e tokenizacao ao campo 'text'.

requirements/base.txt, requirements/local.txt
Atualiza dependencias
pelo commit
1. make build_no_cache
N/A
N/A
N/A
N/A
=> Atualiza dependencias 28032024

collection/wagtail_hooks.py, core/static/admin/css/custom.css, core/templates/modeladmin/inspect.html
Mejora presentación de datos en inspect
-Agrega template
-Agrega estilo para cambio de fuente
-Oculta campos especificados
Por commit
N/A
N/A
-
https://github.com/scieloorg/core/issues/559
N/A
=> (Avance) - Mejorar la presentación de los datos en "inspect"

article/sources/xmlsps.py, researcher/models.py
- Adiciona condição if em Researcher.create_or_update para evitar adição de objetos com researcher Nulo.
- Adiciona paramentros faltantes em Affiliation.create_or_update
pelos commits
python manage.py runscript load_article --script-args admin
N/A
N/A
N/A
N/A
=> Melhora tratamento de dados em Researcher.create_or_update

.envs/.local/.django, .envs/.production/.django, config/settings/base.py, core/utils/utils.py
Adiciona variável de ambiente FETCH_DATA_TIMEOUT
pelos commits
n/a
n/a
n/a
n/a#### Quais são tickets relevantes?
n/a
n/a
=> Adiciona  variável de ambiente FETCH_DATA_TIMEOUT

article/search_indexes.py, index/data/oai/conf/managed-schema.xml
Garante que o ID seja O pid_v3 ou DOI.
Por commit
Acessando a interface do SOLR para URL http://localhost:8983 e verificando o valor dos campos **item.id** e **id**: 
N/A
N/A
N/A
N/A
=> Ajuste o ID para o serviço do OAI.

article/search_indexes.py, requirements/base.txt
Realiza ajustes nos atributos indexados no OAI
Sugiro que seja avaliado o commit 
Para teste manual é necessário acessar o serviço do OAI-PMH: https://oai.scielo.org/request?verb=ListSets 
Atributos definidos no OAI PMH:
- Adicionado PID v2 como identificar
- Adicionado formato do documento
- Adicionado type
- Adicionado assunto (dc:subject)
- Adicionado o campo ``communities`` com o ISSNs
- Adicionado o campo collection com a coleção correspondente
- Adicionado todos os identificadores possíveis na lista de identifiers
- PID v2
- PID v3
- DOI
- URL para o artigo no formato antigo
- Exemplo de URL: https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2019000104001&lang=pt OK
- Adicionado link para licença
- Adicionado source
- Exemplo de source: Acta Cirúrgica Brasileira, …
=> Realiza ajustes nos atributos indexados no OAI

article/models.py, article/search_indexes.py
Adiciona um propriedade no modelo de artigo para ter a origem do artigo ``source``.
Sugiro revisão por commit.
Sugiro rodar a indexação do OAI.
Realizamos essa alteração para que possamos reutilizar o formato de origem do artigo.
N/A
N/A
N/A
=> Adiciona um propriedade no modelo de artigo para ter a origem do artigo ``source``.

article/models.py
Garante que seja indexado os registros mesmo que tenha issue.
N/A
N/A
N/A
N/A
N/A
N/A
=> Garante que seja indexado os registros mesmo que tenha issue.

article/search_indexes.py
Assegura que não tenha erro na geração do source.
N/A
N/A
N/A
N/A
N/A
N/A
=> Assegura que não tenha erro na geração do source.

core/templates/modeladmin/edit.html
Adiciona link para voltar para listagem do modelo na página de edição
pelos commits
Acessar alguma pagina de edicao de algum modelo na area administrativa
N/A
#793 
N/A
=> Adiciona link para voltar para listagem do modelo na página de edição

article/search_indexes.py
Alterar para que collections contenha os ISSNs e communities contenha as coleções com o prefixo ``col``.
Por commit.
Rodando a reindexação dos registro de OAI.
N/A
N/A
N/A
N/A
=> Alterar para que collections contenha os ISSNs e communities contenha as coleções com o prefixo ``col``.

config/settings/production.py
=> Include Enviroment ecurity

config/settings/production.py
Descomenta SECURE_PROXY_SSL_HEADER
N/A
N/A
N/A
N/A
N/A
N/A
=> Descomenta SECURE_PROXY_SSL_HEADER

compose/local/django/Dockerfile, local.yml, production.yml
Remove os serviços pgbounce nos arquivos local.yml e production.yml
pelos commits
1. make up
N/A
N/A
#813 
N/A
=> Remoção do serviço pgbounce para o ambiente local e de produção

issue/api/v1/views.py, journal/api/v1/views.py
Permite a inclusão do parâmetro 'pages' na URL para listar objetos das APIs journal e issue.
pelos commits
1. Acessar: 0.0.0.0:8009/api/v1/issue/?pages=2 ou 0.0.0.0:8009/api/v1/journal/?pages=2
N/A
N/A
N/A
=> Fix Api Journal And Issue

issue/api/v1/serializers.py, journal/api/v1/serializers.py, journal/sources/am_to_core.py
Cria Função get_scielo_journal para Mostrar ScieloJournal.
pelos commits
acessa: 0.0.0.0:8009/api/v1/journal/?title=ACIMED
N/A
API Journal (dados de journal_history Fictícios)
```json
{
"official": {
"title": "Revista de Saúde Pública",
"issn_print": "0034-8910",
"issn_electronic": "1518-8787",
"iso_short_title": "Rev. saúde pública",
"issnl": null
},
"scielo_journal": [
{
"collection_acron": "spa",
"issn_scielo": "0034-8910",
"journal_acron": "rsp",
"journal_history": [
{
"day": null,
"month": "08",
"year": "2001",
"event_type": "ADMITTED",
"interruption_reason": null
},
{
"day": "03",
"month": "01",
"year": "2022",
"event_type": "ADMITTED",
"interruption_reason": "ceased"
}
]
},
{
"collection_acron": "scl",
"issn_scielo": "0034-8910",
"journal_acron": "rsp",
"journal_history": [
{ …
```
=> Melhoria no JournalSerializer: Cria Função get_scielo_journal para Mostrar ScieloJournal

article/scripts/remove_duplicate_articles.py, article/tasks.py, article/tests.py, article/wagtail_hooks.py, requirements/base.txt
Implementa a remoção de artigos duplicados  e adiciona testes para garantir o funcionamento correto.
Pelos commits
1. make django_bash
2. python manage.py test article.tests.RemoveDuplicateArticlesTest
N/A
N/A
N/A
=> Implementa remoção e visualização na interface administrativa de artigos duplicados.

article/migrations/0013_article_article_license.py, article/models.py, article/tasks.py
Remoção das Funções de Transferência de Licença e adiciona task para transferência de Licença.
pelos commits
1. Acessa área administrativa e em tarefas.
2. Criar task transfer_license_statements_fk_to_article_license
N/A
N/A
N/A
=> Remover Funções de Transferência de Licença

journal/api/v1/serializers.py
Adiciona campos adicionais na API de Journal
pelos commits
Acessar: http://0.0.0.0:8009/api/v1/journal/
Os campos adicionais foram inseridos conforme o esquema do modelo Journal no projeto opac_schema
```python
class Journal(Document):
_id = StringField(max_length=32, primary_key=True, required=True)
jid = StringField(max_length=32, required=True, unique=True, )
collection = ReferenceField(Collection, reverse_delete_rule=CASCADE)
timeline = EmbeddedDocumentListField(Timeline)
subject_categories = ListField(field=StringField())
study_areas = ListField(field=StringField())
social_networks = EmbeddedDocumentListField(SocialNetwork)
title = StringField()
title_iso = StringField()
next_title = StringField()
short_title = StringField()
title_slug = StringField()
created = DateTimeField() …
```
=> Adiciona campos adicionais na API de Journal

article/models.py
Garante não levantar exceção para artigos sem referencia de periódico.
Por commit 
N/A
N/A
N/A
N/A
N/A
=> Garante não levantar exceção para artigos sem referencia de periódico.

article/models.py
=> Adiciona um novo tratamento de excessão para a geração do source para o artigo.

journalpage/models.py, journalpage/templates/journalpage/about.html
Adiciona declaração de CLOCKSS na página informativa 
pelos commits
Acessar: http://0.0.0.0:8009/pt-br/journal/{collection_acron3}/{journal_acronym}/
N/A
#842 
N/A
=> Adiciona declaração de CLOCKSS na página informativa 

article/sources/xmlsps.py, article/utils/parse_name_author.py, requirements/base.txt, researcher/models.py
Atualiza packtools e adapta funções  para compatibilidade com a versão 4.7.1
pelos commits
```python
python manage.py runscript load_article --script-args 1
```
N/A
N/A
#847 
N/A
=> Atualiza packtools e adapta funções  para compatibilidade com a versão 4.7.1

article/models.py
Utiliza o ano do issue para produzir o "source" para o protocolo OAI.
N/A
N/A
N/A
N/A
N/A
N/A
=> Utiliza o ano do issue para produzir o "source" para o protocolo OAI.

issue/api/v1/serializers.py, issue/api/v1/views.py, journal/api/v1/serializers.py, journal/api/v1/views.py
Adiciona filtros por data de criação/atualização e inclui esses dados no payload nas APIs de Journal e Issue
pelos commits
Acessar: http://0.0.0.0:8009/api/v1/journal/ ou http://0.0.0.0:8009/api/v1/issue/
N/A
#866 
N/A
=> Adiciona filtros por data de criação/atualização e inclui esses dados no payload nas APIs de Journal e Issue

issue/api/v1/serializers.py, journal/api/v1/serializers.py
Na API de issue, adicionar o idioma das seções do sumário
pelos commits
Acessar: http://0.0.0.0:8009/api/v1/issue/
N/A
N/A
#864 
N/A
=> Na API de issue, adiciona o idioma das seções do sumário

altmetric/wagtail_hooks.py, article/wagtail_hooks.py, book/wagtail_hooks.py, collection/wagtail_hooks.py, config/settings/base.py, core/search_site/views.py, core/templates/wagtailadmin/summary_items/article_summary_item.html, core/templates/wagtailadmin/summary_items/collection_summary_item.html, core/templates/wagtailadmin/summary_items/journal_summary_item.html, core/wagtail_hooks.py, django_celery_beat/button_helper.py, django_celery_beat/wagtail_hooks.py, editorialboard/button_helper.py, editorialboard/wagtail_hooks.py, files_storage/wagtail_hooks.py, institution/button_helpers.py, institution/wagtail_hooks.py, issue/wagtail_hooks.py, journal/button_helper.py, journal/wagtail_hooks.py, location/button_helpers.py, location/wagtail_hooks.py, pid_provider/wagtail_hooks.py, report/wagtail_hooks.py, requirements/base.txt, researcher/wagtail_hooks.py, thematic_areas/button_helpers.py, thematic_areas/wagtail_hooks.py, tracker/wagtail_hooks.py, vocabulary/wagtail_hooks.py
Atualiza versão do wagtail e altera importação para o modulo do wagtail_modeladmin.
pelos commits
make build_no_cache
N/A
N/A
#834 
N/A
=> Atualiza versão do wagtail

altmetric/wagtail_hooks.py, article/wagtail_hooks.py, book/wagtail_hooks.py, collection/wagtail_hooks.py, config/settings/base.py, core/search_site/views.py, core/templates/wagtailadmin/summary_items/article_summary_item.html, core/templates/wagtailadmin/summary_items/collection_summary_item.html, core/templates/wagtailadmin/summary_items/journal_summary_item.html, core/wagtail_hooks.py, django_celery_beat/button_helper.py, django_celery_beat/wagtail_hooks.py, editorialboard/button_helper.py, editorialboard/wagtail_hooks.py, files_storage/wagtail_hooks.py, institution/button_helpers.py, institution/wagtail_hooks.py, issue/wagtail_hooks.py, journal/button_helper.py, journal/wagtail_hooks.py, location/button_helpers.py, location/wagtail_hooks.py, pid_provider/wagtail_hooks.py, report/wagtail_hooks.py, requirements/base.txt, researcher/wagtail_hooks.py, thematic_areas/button_helpers.py, thematic_areas/wagtail_hooks.py, tracker/wagtail_hooks.py, vocabulary/wagtail_hooks.py
Atualiza versão do Django para 5.0.8
pelos commits
make build
Essa branch é uma ramificação de https://github.com/scieloorg/core/pull/846
N/A
N/A
N/A
=> Atualiza versão do Django para 5.0.8

issue/wagtail_hooks.py
Corrige ordem das colunas de Issue na área administrativa
pelos commits
Acessar area administrativa de issue
N/A
#880 
N/A
=> Corrige ordem das colunas de Issue na área administrativa

django_celery_beat/locale/es/LC_MESSAGES/django.po, journalpage/templates/journalpage/about.html, journalpage/templates/journalpage/includes/language.html, locale/en/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po
Adiciona novas mensagens de tradução relacionado a página informativa do periódico
pelos commits
n/a
n/a
n/a
n/a
n/a
=> Adiciona Novas Mensagens de Tradução Delacionado a Página Informativa do Periódico

journal/models.py, journal/wagtail_hooks.py
Custumiza a representação de Journal nos Autocompletelabel
pelos commits
1. Na área administrativa, ir em Issue.
2. Criar um novo Issue
3. Verificar a representação no campo Journal
N/A
#896 
N/A
=> Custumiza a representação de Journal nos Autocompletelabel

journal/models.py
Ajustes na implementação da função __str__ do modelo Journal para validar a presença de atributos issn_print e issn_electronic associados à instância official antes de incluí-los na lista de ISSNs
pelos commits
Criar um Journal vazio na área administrativa
N/A
N/A
#911 
N/A
=> Fix: Journal.__str__

article/sources/xmlsps.py
Fix: parameter extracts_normalized_email
pelos commits
```python 
python manage.py runscript load_articles --script-args admin
```
N/A
N/A
#908 
N/A
=> Fix: parameter extracts_normalized_email

journal/api/v1/serializers.py
Adiciona o campo wos_area e o método get_wos_area no JournalSerializer
pelos commits
1. make up
2. Acessar: http://0.0.0.0:8009/api/v1/journal/
N/A
#913 
N/A
=> Adiciona o campo wos_area e o método get_wos_area no JournalSerializer

config/settings/production.py
Adiciona um param para indicar o uso do sentry.
=> Adiciona um param para indicar o uso do sentry.

journal/api/v1/serializers.py
Remove os campos issn_print e issn_electronic de JournalSerializer
pelos commits
Acessar: http://0.0.0.0:8009/api/v1/journal/
N/A
N/A
#931 
N/A
=> Remove os campos issn_print e issn_electronic de JournalSerializer

journal/tasks.py
Modifica verify para False em fetch_and_process_journal_logo
pelos commits
Build do projeto
N/A
N/A
#935 
N/A
=> Modifica verify para False

journal/api/v1/serializers.py
Adiciona status do periodico ao payload da api de Journal
pelos commits
Acessando API de Journal
N/A
N/A
#933 
N/A
=> Adiciona status do periodico ao payload da api de Journal

pid_provider/base_pid_provider.py, pid_provider/sources/harvesting.py
Fix error UnableLocalError in `./pid_provider/sources/harvesting.py`
pelos commits
Executar task provide_pid_for_opac_xmls
N/A
N/A
#949 
N/A
=>  Fix UnableLocalError

article/tasks.py, article/tests.py, pid_provider/models.py, pid_provider/tasks.py
Cria processamento para criar/atualizar os arquivos XMLVersion no path correto.
pelos commits
REaliza build e verificar os testes
N/A
N/A
#947 
N/A
=> Cria processamento para criar/atualizar os arquivos XMLVersion.

editorialboard/models.py, researcher/models.py
Fix autocomplete NewResearcher
pelos commits
Utilizar autocomplete NewResearcher em EditorialBoard, localizado em Journal
N/A
N/A
N/A
=> Fix autocomplete NewResearcher

pid_provider/tasks.py
fix: condition of function load_file_from_xml
pelos commits
executando a task load_file_from_xml
N/A
N/A
N/A
N/A
=> fix: condition of function load_file_from_xml

pid_provider/tasks.py
fix: corrige extração do acrônimo no caminho do XML usando regex
pelos commits
executando a task
N/A
N/A
N/A
N/A
=> fix: corrige extração do acrônimo no caminho do XML usando regex

pid_provider/tasks.py
fix origin_date load_file_xml_version
pelos commits
execut load_file_xml_version
N/A
N/A
N/A
N/A
=> fix origin_date load_file_xml_version

researcher/choices.py, researcher/models.py, researcher/tasks.py, researcher/tests.py, researcher/wagtail_hooks.py
- Cria um novo modelo ResearcherOrcid e relaciona NewResearcher.
- Cria testes simulandos os casos em que possa haver duplicidade, utiliza chaves especificar recuperação de pesquisadores.
- Cria testes para os métodos de ResearcherOrcid e NewResearcher
- Cria validações para os campos de LATTES e EMAIL.
- Na área administrativa, ao criar objetos em ResearcherOrcid (NewResearcher no admin), cria validações nos campos.
pelos commits
Acessar  área administrativa e na aba NewResearcher.
N/A
CLOSE https://github.com/scieloorg/core/issues/970
CLOSE https://github.com/scieloorg/core/issues/971
CLOSE https://github.com/scieloorg/core/issues/960
N/A
=> Improve: Ajustes na modelagem de pesquisadores.

config/settings/base.py, core/static/admin/js/custom.js, core/users/apps.py, core/users/forms.py, core/users/views.py, core/users/viewsets.py, journal/models.py
Este PR cria um novo custom user model no Wagtail, permitindo maior flexibilidade na autenticação e nos dados de usuário. Além disso, otimiza o carregamento do campo de journals em um formulário, melhorando o desempenho do queryset e a experiência do usuário.
pelos commits
Acessar o formulário de criação do usuário.
N/A
N/A
CLOSE #962 
N/A
=> Cria novo custom user model no Wagtail e melhora performance do formulário de usuário

researcher/models.py, researcher/wagtail_hooks.py
Adiciona validações corretamente no formulário de New Researcher.
Pelos commits
Cria um objeto em newresearcher
N/A
N/A
N/A
=> Fix: form Newresearcher

journal/models.py, journal/wagtail_hooks.py
Na listagem de journals, realiza um fix no button preview about journal
pelos commits
realizando build
N/A
N/A
N/A
N/A
=> Fix: button preview about journal

article/sources/xmlsps.py
Adiciona a opção de popular a data da publicação a partir de `collection_date`.
NA
NA
NA
NA
NA
NA
=> Corrige a obtenção da data de publicação

issue/api/v1/views.py, journal/api/v1/serializers.py, journal/api/v1/views.py
- Adiciona filtro "collection" na API de Journal.
- Realiza improvements na API de Journal e Issue
pelos commits
Acessar: http://0.0.0.0:8009/api/v1/journal/
Acessar: http://0.0.0.0:8009/api/v1/issue/
N/A
N/A
#1008 
N/A
=> Adiciona filtro por acrônimo de coleção 

article/models.py
Fix property no modelo Article.
pelos commits
N/A
N/A
```
In [3]: Article.objects.all().first().journal
Out[3]: <Journal: Ciência e Agrotecnologia or Ciência e Agrotecnologia | Foundation year: 1996>
In [4]: Article.objects.all().first().journal.scielojournal_set.all()
Out[4]: <QuerySet [<SciELOJournal: Brasil cagro>]>
```
CLOSED #1037 
N/A
=> Fix: Article.collections

.envs/.production/.django, config/celery_app.py, config/celery_signals.py, config/settings/production.py, requirements/base.txt, requirements/production.txt
Resolve o erro "too many clients already" ao aprimorar o gerenciamento de conexões de banco de dados para tarefas Celery e configurar dinamicamente opções de pool de conexões.
As principais mudanças são:
* **Limpeza de Conexões Celery:** Garante que conexões de banco de dados antigas sejam fechadas após cada tarefa Celery, prevenindo vazamentos.
* **Configuração Centralizada:** Centraliza a importação dos sinais do Celery em `config/celery_app.py`.
* **Opções de DB por Variável de Ambiente:** Permite configurar o tempo limite de conexão (`DB_CONNECT_TIMEOUT`) e as opções do pool (`DB_POOL_SIZE`, `DB_MAX_OVERFLOW`, `DB_RECYCLE`) via variáveis de ambiente.
* **Melhoria de Logging:** Adiciona logging específico para o processo de limpeza de conexões, facilitando a depuração.
* **Novas …
=> Revisa config de conexão de banco de dados

config/settings/production.py, requirements/production.txt
Fix: Env dependecy production
pelos commits
Realizar build de production.yml
N/A
N/A
N/A
N/A
=> Fix: Env dependecy production

requirements/base.txt
=> Fix: django-silk

pid_provider/api/v1/views.py, pid_provider/tasks.py
=> Fix abordagem configuravel para executar pid provider

requirements/base.txt
Atualiza a versão de packtools 4.11.16 - revisão do módulo que fornece dados para o pid_provider para melhorar desempenho e uso de recursos de memória (no entanto, não houve melhoria neste ponto)
Atualiza a versão de packtools 4.11.16 - revisão do módulo que fornece dados para o pid_provider
Indique as referências utilizadas para a elaboração …
=> Atualiza a versão de packtools 4.11.16 - revisão do módulo que fornece dados para o pid_provider

requirements/base.txt
=> Atualiza packtools 4.11.17

researcher/models.py, researcher/tests.py
- Incluí como validação checksum para ORCID.
- Incluí testes para verificar a validação de checksum de ORCID.
pelos commits
- Executa testes: python manage.py test researcher.tests.TestResearcherOrcid
N/A
N/A
N/A
N/A
=> Fix: Validation Orcid

core/home/models.py
Fix: Pages Home, ListPageJournal e ListPageJournalByPublisher
pelos commits
executar o script: python manage.py import_about path/to/wordpress.xml --clean 
acessar as paginas de home e sobre o scielo
N/A
N/A
N/A
N/A
=> Fix: Pages Home, ListPageJournal e ListPageJournalByPublisher

core/users/forms.py, journal/models.py
- Realiza um fix no required no formulario de user para superuser 
- Realiza um fix no Journal.autocomplete_custom_queryset_filter
pelos commits
- Criar um Journal e preencher o campo main_collection
- Criar um ScieloJournal e setar este Journal acima.
obs: Criar Journal com main_collection com a mesma coleção do user
N/A
N/A
N/A
N/A
=> Fix: Journal autocomplete custom queryset filter
