scieloorg/core

requirements/base.txt
wagtail 4.2.2 depends on Django<4.2 and >=3.2
Reverts scieloorg/core#207
=> Revert "Bump django from 4.1.8 to 4.2.1"

pid_provider/xml_sps_adapter.py, xmlsps/models.py, xmlsps/wagtail_hooks.py
Evita problema de IntegrityError ao criar / obter XMLIssue e XMLJournal
```
<class 'django.db.utils.IntegrityError'>
duplicate key value violates unique constraint "xmlsps_xmlissue_journal_id_pub_year_volu_acd3d48b_uniq" DETAIL: Key (journal_id, pub_year, volume, number, suppl)=(4, 2017, 89, 1, 0) already exists.
```
por commits 
```console
python manage.py runscript provide_pid_for_opac_xmls --script-args adm begin_date end_date limit pages
```
sendo:
- begin_date e end_date no formato YYYY-MM-DD
- limit - quantidade por requisição
- pages - quantidade de páginas a consultar, se quiser impor um limite de requisições, caso contrário as consultas irão até o final
```console
python manage.py runscript provide_pid_for_am_xmls --script-args adm
```
n/a
n/a
n/a
n/a
=> Evita problema de IntegrityError ao criar / obter XMLIssue e XMLJournal e algumas melhorias

article/models.py, book/models.py, book/sources/oai_books.py, collection/models.py, config/settings/base.py, config/urls.py, core/models.py, doi/models.py, institution/models.py, issue/models.py, journal/models.py, journal_and_collection/models.py, location/models.py, location/scripts/bulk_cities.py, location/scripts/bulk_states.py, pid_provider/models.py, requirements/base.txt, researcher/models.py, vocabulary/models.py, xmlsps/models.py
Adicionar suporte para  AutoCompletePanel em todos os campos Many-to-Many e ForeignKey
A partir do commit https://github.com/scieloorg/core/pull/323/commits/a6573ffa048d6830b51f2b1a6e699e19ad58662d
1. make build
2. make up
3. Acessa: [0.0.0.0:8000/admin/](http://0.0.0.0:8000/admin/)
N/A
N/A
https://github.com/scieloorg/core/issues/322
https://wagtail-autocomplete.readthedocs.io/en/latest/
=> Adicionar suporte para  AutoCompletePanel em todos os campos Many-to-Many e ForeignKey

article/search_indexes.py, article/templates/search/indexes/article/article_compile.txt
Adiciona o XOAI para o índice do OAI.
Sugiro que a validação seja feita por commit.
Ao alterar qualquer artigo no modelo de article deve ser gerado uma nova entrado no core **oai**, repare no campo: **item.compile**
Esse PR é uma melhoria do PR: https://github.com/scieloorg/core/pull/328
O serviço o OAI, com os dados dos artigos: 
Não há tíquete para essa demanda.
N/A
=> Adiciona o XOAI para o índice do OAI.

pid_provider/models.py, pid_provider/wagtail_hooks.py
Apresenta na área restrita, nas listas de PidRequest, PidProviderXML, PidChange, as datas de atualização ou criação
por commits
- Acesse área restrita
- Acesse o menu Pid Provider
- Entre em Pid Request, Pid Provider XML e Pid Change e observe a última coluna é "created_updated"
Isso economiza espaço se é desejável saber apenas a data mais recente seja de atualização ou de criação
n/a
n/a
=> Apresenta na área restrita, nas listas de PidRequest, PidProviderXML, PidChange, as datas de atualização ou criação

pid_provider/wagtail_hooks.py
Adiciona `issue__pub_year` a list_filter de PidProviderXMLAdmin
por commits
Acessar a área restrita
Acessar Pid Provider > Pid Provider XML
Visualizar na lista de filtro `issue__pub_year`
n/a
n/a
n/a
n/a
=> Adiciona `issue__pub_year` a list_filter de PidProviderXMLAdmin

journal/models.py
Cambiao en la presentacion de los campos adoptando Autocomplete
Subject Descriptors
Web of Knowledge Subject Categories
text languages
abstract languages
index at
Además se hace el ordenamiento en Subject Descriptors, Web of Knowledge Subject Categories e index at
por commit
Revisión de catálogos
N/A
https://github.com/scieloorg/core/issues/393
N/A
=> Cambios en presentación de campos ManyToMany

requirements/base.txt
Atualiza a versão de packtools para 3.2.3
Corrige o valor do atributo `XMLWithPre.article_publication_date` usado pelo pid provider, obtido de `packtools.sps.models.dates.ArticleDates`
por commits
```console
python -m pip install packtools@https://github.com/scieloorg/packtools/archive/refs/tags/3.2.3.zip
```
Problema ocorria ao atribuir pid para artigo que contém data incompleta e pub-type='epub' (versão anterior a SPS 1.8):
```xml
<pub-date pub-type="epub"><year>2020</year></pub-date>
```
n/a
n/a
n/a
n/a
=> Atualiza a versão de packtools para 3.2.3

pid_provider/models.py
Adiciona em PidProviderXML.public_items a condição de registros que possuem `current_version__pid_v3__isnull=False` para evitar que se tente gerar Article a partir XML que estejam incompletos 
por commits
Processando a tarefa load_articles
n/a
n/a
n/a
n/a
=> Adiciona em PidProviderXML.public_items a condição de registros que possuem `current_version__pid_v3__isnull=False`

article/sources/xmlsps.py, article/tasks.py
Adiciona um novo parâmetro v3 em load_article que serve como identificador. Além disso, foi inserido um novo bloco de try-except para registrar possíveis erros na obtenção do XML.
https://github.com/scieloorg/core/commit/7402adfc68de78e75684bde227d6ec6d7174086f
1. make up
2. make django_bash
3. python manage.py runscript load_article --script-args admin
N/A
N/A
N/A
N/A
=> Adiciona Novo Parâmetro e Bloco de Registro de Erros para load_article

journal/wagtail_hooks.py
Coloca journal como primeira coluna de SciELOJournal e acrescenta as colunas status e filtro status e collection
por commits
Acessando a página SciELO Journals
A ordenação por título de journal não funciona, pois journal é um FK.
Fica pendente dar solução para a ordenação por título
Relacionado com #530 
n/a
=> [Melhoria UX] Coloca journal como primeira coluna de SciELOJournal e acrescenta as colunas status e filtro status e collection

journal/sources/am_data_extraction.py, journal/sources/am_to_core.py, journal/wagtail_hooks.py
Corrige a carga de journal:
- erro de registro de coleção principal
- erro de obtenção de issn print ou eletrônico
por commits
Executando antes da alteração, alguns UnexpedtedEvent são gerados
```console
python manage.py runscript load_journal_from_am_journal --script-args adm prt
python manage.py runscript load_journal_from_am_journal --script-args adm cub
```
Os problemas ocorreram com as duas coleções.
Executando após a alteração, os erros não acontecem
```console
python manage.py runscript load_journal_from_am_journal --script-args adm prt
python manage.py runscript load_journal_from_am_journal --script-args adm cub
```
n/a
n/a
n/a
n/a
=> Corrige a carga de journal

journal/sources/am_to_core.py, location/models.py
Corrige a função 'create_or_update_location' para preencher os dados corretamente no modelo Location.
Pelos commits
1. make django_bash
2. python manage.py runscript load_journal_from_am_journal --script-args {username}
N/A
https://github.com/scieloorg/core/issues/658
N/A
=> Corrige a função 'create_or_update_location' para preencher os dados corretamente no modelo Location.

config/settings/production.py, requirements/production.txt
- Atualiza o sentry-sdk para a versão 2.5.1 com integração para Django.
- Altera a configuração do traces_sample_rate no arquivo production.py para utilizar um valor padrão de 1.0.
pelo commits
1. make build_no_cache
2. make up
N/A
N/A
N/A
N/A
=> Atualização do Sentry SDK e Configurações de Monitoramento

tracker/tasks.py
Permite especificar um tipo de error e uma data para apagar os errors de UnexpectedEvents
pelos commits
1. Executa a task delete_unexpected_events  com os paramentros {"start_date": '2023-01-01'}
N/A
N/A
N/A
N/A
=> Melhora Task delete_unexpected_events

core/utils/rename_dictionary_keys.py, issue/sources/article_meta.py, issue/utils/issue_utils.py
Corrige a coleta de dados de issue do articlemeta.
O principal problema é que em no lugar de 
```python
issue_dict = rename_dictionary_keys(
data_issue["issue"], correspondencia_issue
)
```
no lugar de
```python
data_issue["issue"]
```
deveria ser
```python
[data_issue["issue"]]
```
Mas estava difícil de identificar o problema. Foi necessário deixar a função `rename_dictionary_keys` mais legível e adicionar  logging na função.
por commits
Executando a tarefa de coleta de dados de issue do articlemeta
n/a
n/a
n/a
n/a
=> Corrige a coleta de dados de issue do articlemeta

article/models.py, article/tasks.py
Corrige forma dos artigos serem selecionados por data.
pelos commits
Executar carga de artigos
N/A
N/A
#869 
=> Fix: Corrige forma dos artigos serem selecionados por data.

requirements/base.txt
Remove dependência wagtail-autocomplete==0.11.0
pelos commits
realizando build do projeto
N/A
N/A
N/A
N/A
=> Fix: Remove dependency wagtail-autocomplete==0.11.0

config/urls.py
Verificar a instalação de django-silk antes de incluir nas urls
pelos commits
build do projeto
n/a
n/a
n/a
n/a
=> Fix: Verify silk instaled app urls

config/settings/base.py, pid_provider/api/v1/views.py, pid_provider/tasks.py
Este Pull Request introduz a funcionalidade de alternar entre o processamento **assíncrono (via Celery)** e **síncrono** de arquivos ZIP para a provisão de PIDs. Anteriormente, todas as requisições de PID eram processadas de forma assíncrona, o que, embora robusto para grandes volumes, adicionava uma camada de complexidade e latência para operações que poderiam ser concluídas rapidamente.
Com a adição da variável de ambiente `RUN_ASYNC`, é possível configurar a aplicação para processar a tarefa `task_provide_pid_for_xml_zip` de forma síncrona (`RUN_ASYNC=0`) ou assíncrona (`RUN_ASYNC=1`). Isso permite otimizar o fluxo para casos onde a resposta imediata é preferível e a carga de trabalho permite o processamento síncrono, ou manter o comportamento assíncrono para operações mais pesadas e …
=> Abordagem configuravel para executar pid provider

journal/api/v1/serializers.py, location/models.py
Adiciona dados de licensa e location na API de Journal
pelos commits
acessar: http://0.0.0.0:8009/api/v1/journal/?issn_electronic=2317-6326
format location:
```json
"location": {
"city_name": "São Paulo",
"state_name": null,
"state_acronym": "SP",
"country_name": "Brasil",
"country_acronym": "BR",
"country_acron3": "BRA"
},
```
format journal_use_license:
```json
"journal_use_license": "BY",
```
N/A
#1099 
N/A
=> Adiciona dados de licença e location na API de Journal
